# Generated by Django 4.0.5 on 2022-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_usersettings_usernotificationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinList',
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='show_on_search',
            field=models.BooleanField(default=True),
        ),
    ]
